# Generated by Django 5.0.6 on 2024-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='receipe_images')),
            ],
        ),
        migrations.DeleteModel(
            name='Receipe',
        ),
    ]
